spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: lukesh
    password: querty
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
